
    <main>
        <section class="ritual-chamber">
            <h2>Scribing Digital Runes</h2>
        </section>

        <section id="grimoire" class="grid2">
            <div class="spell-card2">
                <h2>Enchantment</h2>
                <p>A strict line of cause and effect binds actions to their consequences. Yet, synchronicity weaves through this logic, offering acausal, deeply meaningful connections. True enchantment requires spoken words to manifest its magic. Most often, it begins with the quiet utterance of a spell or charm. This magic is elevated by surrounding rituals—ceremonies, visual artistry, or the resonant ring of a chime, bell, and song. Even a gifted storyteller can cast this spell, leaving an audience entirely spellbound. Musicians hold a unique version of this power, blending instruments and raw vocalizations. In their highest form, these melodic incantations can move mountains.</p>
<p>"Hear me, and make all spirits subject unto me, so that every spirit of the firmament and of the ether, upon the earth and under the earth, on dry land and in the water, of whirling air, and of rushing fire, and every spell and scourge of God may be obedient unto me."</p>
<p>"Hear me, and make all spirits subject unto me, so that every spirit of the firmament and of the ether, upon the earth and under the earth, on dry land and in the water, of whirling air, and of rushing fire, and every spell and scourge of God may be obedient unto me."</p>
<p>Procol oh procol este profani. Barlasti ompala. In the name of the Mighty and Terrible One, I proclaim that I have banished the shells unto their habitations. I invoke Tahuti, the Lord of Wisdom and of Utterance; the god that cometh forth from the veil. Oh thou, majesty of the godhead, wisdom-crowned Tahuti, Lord of the gates of the universe. Thee, thee I invoke. Oh thou of the ibis head. Thee, thee I invoke. Thou who wieldest the wand of double power. Thee, thee I invoke. Thou who bearest in thy left hand the rose and cross of light and life. Thee, thee I invoke. Thou whose head is as an emerald, and thy nemyss as the night sky blue. Thee, thee I invoke. Thou whose skin is a flaming orange as though it burned in a furnace. Thee, thee I invoke.</p>
<p>Behold, I am yesterday, today, and the brother of tomorrow. I am born again and again. Mine is the unseen force whereof the gods are sprung, which is as life unto the dwellers in the Watchtowers of the Universe. I am the charioteer of the east; Lord of the past and the future. I see by my own inward light; Lord of resurrection who cometh forth from the dust, and my birth is from the house of death. Oh ye two Divine hawks upon your pinnacles who keep watch over the universe. Ye who company the Bier to the house of rest, who pilot the ship of Ra, ever advancing onwards the heights of heaven. Lord of the shrine which standeth in the center of the earth. Behold! He is me and I in him. Mine is the radiance wherein Ptah floateth over the firmament. I travel upon high. I tread upon the firmament of Nu. I raise a flashing flame with the lightening of mine eye. Ever rushing on in the splendor of the daily glorified Ra, giving my life to the dwellers of earth. If I say come up upon the mountain, the celestial waters shall flow at my command. For I am Ra incarnate, Kephra created in the flesh. I am the idolar of my father Tnu, Lord of the city of the sun. The god who commands is in my mouth. The god of wisdom is in my heart. My tongue is the sanctuary of truth and a god sitteth upon my lips. My word is accomplished every day, and the desire of my heart realizes itself as that of Ptah when he created his works. I am eternal, therefore all things are as my designs. Therefore do thou come forth unto me from thine abode in the silence, unutterable wisdom, all light or power.</p>
<p>Thoth. Hermes. Mercury. Odin. By whatever name I call thee thou art still nameless to eternity. Come thou forth I say, and aid and guard me in this work of art. Thou star of the east that didst conduct the magi. Thou art the same all present in heaven and in hell. Thou that vibratest between the light and the darkness, rising, descending, changing ever, yet ever the same. The sun is thy father; thy mother the moon. The wind hath borne thee in it's bosom and earth hath ever nourished the changeless god head of thy youth. Come thou forth I say, come thou forth and make every spirit of the firmament and of the ether, upon the earth and under the earth, on dry land and in the water, of whirling air and of rushing fire, and every spell and scourge of God the Vast One may be obedient unto me.</p>
<hr>
<p>The invocation above is popular and avaialbe in audio format. You can find free copies on spotify and youtube. Someone took the original version and mixed with a classical egyption like sountrack.</p>
<a href="https://open.spotify.com/track/78fUt4i3TBv69GEszc3A9y">Invocation of Thoth</a>
<p>No restrictions exactly, A charm can be simply a ritual action, with or without words, intrumental linguistic or not, symbolic or not. Its just amazing what you can create with music. Enchantments can bless, cure, bring luck, bad fortune, love, loss, or change the weather.</p>
            </div>
       
        </section>
    </main>


